Enhance default value field
bdunderscore/modular-avatar pull request #1125
Opened 2024-09-09 11:45 UTC by nekobako

Closes #1124 ですが、対応ブランチを main から切ると #1119 と #1121 とコンフリクトするため、このブランチには一旦これら 2 件の PR のコミットを含めています。
上記 2 件の PR がそのままマージされたらこのブランチを rebase して force push する予定です。(マージされなかったら書き直します)

2024-09-14 01:07 UTC, bdunderscore commented
コンフリクトするPRをマージしました 👍

2024-09-14 02:09 UTC, nekobako commented
rebase して force push しました！

2024-09-14 02:39 UTC, bdunderscore commented
Draftのままですがレビュー準備大丈夫ですか？

2024-09-14 02:40 UTC, nekobako commented
わすれてました！

2024-09-14 02:46 UTC, bdunderscore requested changes

2024-09-14 02:46 UTC, bdunderscore commented on Editor/Inspector/Parameters/DefaultValueField.cs
> +                : string.Empty);
`NaN` を入力すると `-2147483648` になるようです。
また、`255`の値を`Infinity`に変えると保持される模様（なんで？）

まぁ、大きな問題ではないけど。

2024-09-14 02:46 UTC, bdunderscore commented on Editor/Inspector/Parameters/DefaultValueField.cs
> +                ? Mathf.Clamp(value, -1, 1).ToString(CultureInfo.InvariantCulture)
VRCSDKは実際にClampしていますか？
保存されたデータと実態が異なるとバグの源なので、できればそのままの値を表示しつつ変更時にクランプ処理を施したいですね・・・

2024-09-14 03:06 UTC, nekobako commented on Editor/Inspector/Parameters/DefaultValueField.cs
> +                ? Mathf.Clamp(value, -1, 1).ToString(CultureInfo.InvariantCulture)
> VRCSDKは実際にClampしていますか？

VRCSDK も範囲外の値を保存するようになっていて、Inspector の表示とアップロード後の VRChat で Clamp されるのを確認しています。

https://github.com/user-attachments/assets/007ee3f9-bc43-4f6a-962f-dffe812dcf5a

(0:16~ Clamp された表示をさらに編集すると変な値になるのは Canny 案件かな…　範囲外だから問題なさそうだけど)


> 保存されたデータと実態が異なるとバグの源なので、できればそのままの値を表示しつつ変更時にクランプ処理を施したいですね・・・

タイプを変えて再び戻したときに元の値が残っているのは利点かなと思いましたが、バグの源なのはそうですね…
タイプか値を変更したら Clamp してしまうようにしましょうか

2024-09-14 03:22 UTC, bdunderscore commented on Editor/Inspector/Parameters/DefaultValueField.cs
> +                ? Mathf.Clamp(value, -1, 1).ToString(CultureInfo.InvariantCulture)
編集時範囲外の値をはじくことにより、「表示された値と違う値が処理されて壊れた」事案が避けられるので今後のバグ対応がしやすくなるかなと思ったり

2024-09-14 03:24 UTC, bdunderscore commented on Editor/Inspector/Parameters/DefaultValueField.cs
> +                ? Mathf.Clamp(value, -1, 1).ToString(CultureInfo.InvariantCulture)
あ、「タイプか値」ですね。それで大丈夫だと思います！

2024-09-14 07:17 UTC, nekobako commented on Editor/Inspector/Parameters/DefaultValueField.cs
> +                ? Mathf.Clamp(value, -1, 1).ToString(CultureInfo.InvariantCulture)
対応しました！

2024-09-14 07:17 UTC, nekobako commented on Editor/Inspector/Parameters/DefaultValueField.cs
> +                : string.Empty);
こちらも対応しました

2024-09-15 00:52 UTC, bdunderscore approved these changes
ありがとうございます！

2024-09-15 00:53 UTC, merged