Fix menu item float value
bdunderscore/modular-avatar pull request #1140
Opened 2024-09-14 10:40 UTC by nekobako

Closes #1139 です。

ParameterValueLo / ParameterValueHi がこれでいいのかは微妙ですが、小数の判定が 0.01f だったので +0.005f/-0.005f にしてみました。

2024-09-15 00:53 UTC, bdunderscore requested changes

2024-09-15 00:53 UTC, bdunderscore commented on Editor/ReactiveObjects/ParameterAssignerPass.cs
> +                        : VRCExpressionParameters.ValueType.Bool;
ちょっと ?: が複雑になりすぎている気がするのでif文に変更お願いします

2024-09-15 02:50 UTC, bdunderscore commented
あ、1.10.0-rc.5 に間に合わなかった・・・😇

2024-09-15 02:51 UTC, bdunderscore requested changes

2024-09-15 02:51 UTC, bdunderscore commented on Editor/ReactiveObjects/ParameterAssignerPass.cs
> +                    }
この順番だと間違ったbool判定になるのでは？

- value=4 (ExpressionParametersValueType=int)
- value=0 (ExpressionParametersValueType=bool)

2024-09-15 03:04 UTC, nekobako commented on Editor/ReactiveObjects/ParameterAssignerPass.cs
> +                    }
1. `valueType` は `Bool`

2. `mami.Control.value` = 4
    - `valueType` は `Bool` で `type` は `Int`
    - `valueType == Bool` を満たすので `valueType` が `Int` になる
3. `mami.Control.value` = 0
    - `valueType` は `Int` で `type` は `Bool`
    - `valueType == Bool` も `type == Float` も満たさないので `valueType` は変わらない

4. `valueType` は `Int`

となるはずで、

```
Test(new[] { 2.0f, 1.0f, 0.0f }, VRCExpressionParameters.ValueType.Int);
```

のテストが同じ内容だと思います。

2024-09-15 03:06 UTC, nekobako commented on Editor/ReactiveObjects/ParameterAssignerPass.cs
> +                        : VRCExpressionParameters.ValueType.Bool;
if 文に変更しようとしていたらマイナスの扱いが間違っていることに気づいたので一緒に修正しました。

2024-09-15 09:26 UTC, nekobako commented on Editor/ReactiveObjects/ParameterAssignerPass.cs
> +                    }
変数名が紛らわしかったので変更しました。

2024-09-16 02:32 UTC, bdunderscore approved these changes

2024-09-16 02:33 UTC, merged