Improve InferPrefixSuffix / Support using Humanoid Rig on Setup Outfit
bdunderscore/modular-avatar pull request #1167
Opened 2024-09-16 15:59 UTC by Sayamame-beans

- fix: #1151 
- fix: #1152 
- fix: #429 
- improve: #874 
- fix: #908 

## 接頭辞/接尾辞 推定の改善

- Hipsの辞書を確認し、一致したらその前後がprefix/suffixである
- 一致するものがなければ、従来の処理(アバターHipsとの比較)を行う

詳細は https://github.com/bdunderscore/modular-avatar/issues/1151#issuecomment-2351949347

## Setup Outfitやボーン名変更において、Humanoidからの取得に対応

衣装がHumanoidであれば、衣装のHumanoidボーンに対しては対応するアバターのHumanoidボーンを優先して確認するようになります。
また、アバターのボーンを確認する際は辞書を見る前にHumanoidから確認します。

## 備考

Setup Outfit周辺の処理を読み違えていたらすみません。
その他の懸念点等については追加するコメントをご参照ください。

2024-09-16 16:11 UTC, Sayamame-beans commented
変更内容に応じてcrowdin上のテキストを変更する必要があるかもしれません。
後ほど確認し、必要そうならsuggest出してこちらで報告します。

2024-09-16 16:18 UTC, Sayamame-beans commented
あと動作確認が足りない(衣装/アバター)ので、後ほど手元でも色々試しますが、もし気になる点があれば検証していただけると助かります。
びしょぬれのしずくさんについては他の方に協力を依頼する予定です。

2024-09-16 23:23 UTC, Sayamame-beans commented
> 変更内容に応じてcrowdin上のテキストを変更する必要があるかもしれません。 後ほど確認し、必要そうならsuggest出してこちらで報告します。

https://github.com/bdunderscore/modular-avatar/blob/3648348184bad2e304b031766293eda4fa616ca4/Editor/Localization/ja-JP.json#L239
に大文字と小文字を区別しない旨を追加するだけで済みそうです。変更したらお知らせします。

Crowdin側の変更箇所の見通しが立ったのでReady for reviewとします。

2024-09-17 05:39 UTC, Sayamame-beans commented on Editor/Inspector/MergeArmatureEditor.cs
> +                    HeuristicBoneMapper.RenameBonesByHeuristic(target, avatarAnimator: avatarAnimator);
ここでは衣装側Animator(Humanoid)を見ていないのですが、理由として、MergeArmatureが取り付けられているボーン以下にあるHumanoidボーンは何か、を絞り込む方法がパッと思いつかなかったというのがあります。
良い感じの方法があれば、ここでもHumanoidボーン判定を使いたい気がします。

2024-09-17 18:20 UTC, Sayamame-beans commented
Crowdin上の日本語翻訳を変更しました。
(他のすべての日本語翻訳も調整しましたので、ご確認いただけると幸いです。)

2024-09-18 02:55 UTC, bdunderscore commented
大きな仕様変更で1.10.0のスコープを広げたくないので、申し訳ないけど1.10.1まで保留です

2024-09-18 05:20 UTC, Sayamame-beans commented on Editor/Inspector/MergeArmatureEditor.cs
> +                    HeuristicBoneMapper.RenameBonesByHeuristic(target, avatarAnimator: avatarAnimator);
よく考えたら、HeuristicBoneMapperに処理対象として渡されるのがMergeArmatureの取り付けられているボーン以下だけですね…
その中でHumanoidに一致したらアバターの〜と話が続くので、SetupOutfit時と特に変わらない気がしてきました。
後ほど衣装側のHumanoidを取得する処理を追加します。

2024-09-20 12:56 UTC, Sayamame-beans commented on Editor/Inspector/MergeArmatureEditor.cs
> +                    HeuristicBoneMapper.RenameBonesByHeuristic(target, avatarAnimator: avatarAnimator);
やりました(多分動く)

2024-09-23 13:06 UTC, Sayamame-beans commented
(もしかしたら1021の"一段深くする"もやるかも…? 気が向いたら…)

2024-09-28 06:00 UTC, Sayamame-beans commented
> (もしかしたら1021の"一段深くする"もやるかも…? 気が向いたら…)

やりました

2024-10-12 23:33 UTC, bdunderscore requested changes
全体的なコメントとして、そろそろユニットテストが欲しいところですね・・・

2024-10-12 23:33 UTC, bdunderscore commented on Editor/HeuristicBoneMapper.cs
> +                        if (avatarBone != null)
考え方としては、精度の高い→低い順ですべてのボーンを処理し、処理できた場合は親からも子からも候補として外す、といった感じですね・・・そのため、直接名前でマッチした場合は被りマッチングで同じボーン名になることを避けたいです

2024-10-12 23:33 UTC, bdunderscore commented on Editor/HeuristicBoneMapper.cs
>          {
ちょっと複雑になってきてるのでリファクタリングが必要そうですね・・・
それと、ここまで複雑になるとさすがにユニットテストが必要そうです

2024-10-12 23:33 UTC, bdunderscore commented on Editor/Inspector/MergeArmatureEditor.cs
> +                    }
この辺の処理はSetup Outfitとかぶってそうなので一か所にまとめられるかな？

2024-10-12 23:33 UTC, bdunderscore commented on Editor/SetupOutfit.cs
> +                    if (hipsCheck != null && hipsCheck.parent == outfitRoot.transform)
Hipsが衣装直下の場合、今の処理だと衣装ルートにMerge Armatureが入り、Armature直下にメッシュが移動することになる。問題になるかというと微妙ではあるけど・・・

2024-10-12 23:33 UTC, bdunderscore commented on Editor/HeuristicBoneMapper.cs
> +            Dictionary<Transform, HumanBodyBones> humanoidBones = null
ここは `HumanDescription.boneName` を応用したほうが既存のロジックと馴染みやすい気がする？

2024-10-12 23:33 UTC, bdunderscore commented on Editor/SetupOutfit.cs
> +                    }
Hipsの判定に失敗した場合、衣装アニメーターの判定が信用できないという判定はあったほうがいいかも？

2024-10-12 23:33 UTC, bdunderscore commented on Editor/SetupOutfit.cs
> +                    if (outfitHips != null) return true; // found an exact match, bail outgit
outgit? 🤔

2024-10-12 23:33 UTC, bdunderscore commented on Editor/SetupOutfit.cs
>                      }
この処理が重複しています。

2024-10-12 23:33 UTC, bdunderscore commented on Runtime/ModularAvatarMergeArmature.cs
> +
delegateや値をエディタアセンブリから差し込むほうがシンプルでいいです

2024-10-12 23:33 UTC, bdunderscore commented on Runtime/ModularAvatarMergeArmature.cs
>              // GameObject we're attached to.
Hipsが衣装直下の場合、この辺の処理が失敗する（Hipsが一人っ子であることに依存）

2024-10-13 08:18 UTC, Sayamame-beans commented on Editor/SetupOutfit.cs
> +                    if (hipsCheck != null && hipsCheck.parent == outfitRoot.transform)
あんまり綺麗じゃない(し何が起こるかあんまり分からない)という感じですかね～
そのままにしておきます

2024-10-13 08:19 UTC, Sayamame-beans commented on Editor/SetupOutfit.cs
> +                    if (outfitHips != null) return true; // found an exact match, bail outgit
多分元のコメントから入ってますね…(コピペで持って来たはず)

2024-10-13 08:25 UTC, Sayamame-beans commented on Editor/SetupOutfit.cs
>                      }
重複していないはずです(575行目で別の変数に代入し、それで書き換えた同種類の処理のはず)
纏めるのも(変数以外で)微妙に異なるので、フラグ切り替え式や引数がnullかどうかで判断するみたいなことになって、分かりづらさが出てきそうです…?

2024-10-13 10:01 UTC, Sayamame-beans commented on Editor/Inspector/MergeArmatureEditor.cs
> +                    }
outfitAnimator取得以降の部分を纏めると良い感じのバランスになりそうかもですね
検討します

2024-10-13 16:43 UTC, Sayamame-beans commented on Editor/HeuristicBoneMapper.cs
> +            Dictionary<Transform, HumanBodyBones> humanoidBones = null
なるほど…(`HumanBone.boneName`ですかね?)
新しくDictionaryを作るのではなく、HumanBone構造体を利用した方が良いのでは、ということでしょうか…
(既存のロジックと馴染みやすいというのはピンときていませんけれど)

あ～…しかし、KeyがTransformでValueがHumanBodyBonesなのでちょっと噛み合わない気もします?

2024-10-13 17:37 UTC, Sayamame-beans commented on Runtime/ModularAvatarMergeArmature.cs
> +
こんな感じでしょうか?
https://github.com/bdunderscore/modular-avatar/pull/1167/commits/2fa86728233d2a8facc0766d762f4804e35f2db3

2024-10-13 17:38 UTC, Sayamame-beans commented on Editor/Inspector/MergeArmatureEditor.cs
> +                    }
https://github.com/bdunderscore/modular-avatar/pull/1167/commits/6f391513179f327274a16f99d7165b0f4ea08d8e

2024-10-13 17:39 UTC, Sayamame-beans commented on Editor/HeuristicBoneMapper.cs
> +                        if (avatarBone != null)
https://github.com/bdunderscore/modular-avatar/pull/1167/commits/b4b7a24a22225aae35b8cbb743ddd80c2005e318

2024-10-14 01:24 UTC, bdunderscore commented on Editor/HeuristicBoneMapper.cs
> +            Dictionary<Transform, HumanBodyBones> humanoidBones = null
`HumanDescription`のほうです。`animator.avatar.humanDescription.boneName`でアクセスできるやつ。

主な理由は、この時点ではアバターが衣装のボーン構造に吸い込まれる対策を立ててない（とはいえ、ほかの問題もあるが・・・）ので、AnimatorのHumanBodyBonesに依存するとマッチングに不確定要素が入るからです・・・

2024-10-14 01:25 UTC, bdunderscore commented on Editor/SetupOutfit.cs
>                      }
あー見落としてた。こちらの勘違いです。

2024-10-14 01:25 UTC, bdunderscore commented on Runtime/ModularAvatarMergeArmature.cs
> +
そんな感じでお願いします

2024-10-14 01:31 UTC, Sayamame-beans commented on Editor/HeuristicBoneMapper.cs
> +            Dictionary<Transform, HumanBodyBones> humanoidBones = null
> アバターが衣装のボーン構造に吸い込まれる

ここでは衣装のhumanoid boneを集めているはず…? (明確化のために変数名変更済み)

2024-10-15 01:30 UTC, Sayamame-beans commented on Editor/HeuristicBoneMapper.cs
>          {
> ちょっと複雑になってきてるのでリファクタリングが必要そうですね・・・
> それと、ここまで複雑になるとさすがにユニットテストが必要そうです

これどうしましょうか…
特にユニットテストは中々渋そうな感じもしますけれど

2024-10-20 05:02 UTC, Sayamame-beans commented on Editor/SetupOutfit.cs
> -                var avatarAnimator = avatarRoot.GetComponent<Animator>();
avatarAnimatorは上方で取得してるので省いています(多分)
キャッシュの都合とかでマズそうであれば再取得するようにします

2024-10-20 10:38 UTC, Sayamame-beans commented on Editor/HeuristicBoneMapper.cs
>          {
出来た気がします → https://github.com/bdunderscore/modular-avatar/pull/1167/commits/dcdb8e9632e72ee783d42348bb63a96d2250af17

2024-11-02 22:17 UTC, bdunderscore approved these changes

2024-11-02 22:17 UTC, merged