Add SubMenu Creator Module
bdunderscore/modular-avatar pull request #145
Opened 2022-12-09 07:40 UTC by raiti-chan

#144 
自分の環境で使用しているコードです。

#### 懸念点
- 既存の`MenuInstaller`が`SubMenuCreator`を参照できるようにするために結構なコードの変更を加えている(動作自体は参照先を選択するためのポップアップが追加されただけ)
- `SubMenuCreator`で追加された項目が`MenuInstaller`で追加される項目より上に必ず来てしまうため複合した順序のレイアウトが難しい
- アバターに設定されたメニューが実質2回複製されてしまう。(SubMenuCreatorとMenuInstallerでそれぞれ複製される)

実装方針に沿ってない可能性が十分あるのでレビュー頂ければ対応いたします

2022-12-09 18:40 UTC, bdunderscore commented
コードレビューの前にちょっとUXと今後の開発との干渉の確認が必要ですね。

まず目的の確認としては、 #144 を見たところ、主な目的は「複合的なアセットで複数のMenu Installerで導入されるメニューを一つにまとめたい」とみていますが、他にも用途も考えられます。例えば、「同じギミック作者のデフォルトインストール位置をまとめる」とか「TogglesやClothingなどの大きなくくりに同じ系統のギミックをまとめる」という用途も考えられます。ただし、「大きなくくり」となるとアイコンなどを誰が指定するんだ、という問題があるので、いったん置いておきます。

また、似たような既存の仕組みとしては、https://github.com/hai-vr/av3-expressions-menu-hierarchy-editor がありますね。サブメニューをGameObjectとして扱うことでものすごく編集しやすくするアセットです。これもMAの方針とはマッチし、そのうち統合、もしくはアイデアとして採用しようかなと考えていた仕組みですが、規模が大きいので1.0では見送りました。

この辺のUI/UXはまだ定まりきってないし、一度コンポーネントを作ってしまうと今後ずっと維持しないといけないので、まずはいったん、今回の要望を新規コンポーネントを使わずに実装できるか考えたいところです。

たとえば、Menu Installerの指定先に、アバターにあらかじめ入っているメニューアセットではなく、別のMenu Installerのインストールするメニューを指定できるようにするパッチだったら、今の仕様（保存形式）を大きく変えずに「複合的なアセットで複数のMenu Installerで導入されるメニューを一つにまとめる」という目的が果たせます。

そのうえで「まったく同じメニューを同じ場所に複数回導入しない」設定や、「空のメニューの場合は省略」設定も入れれば、「同じギミック作者のデフォルトインストール位置をまとめる」こともできるようになります。

別のメニューに入れる、となるとParametersとの干渉を考える必要もあります。この場合は「もともとのMenu Installerの位置のParametersコンテキストを参照」する仕様のほうがよさそうな気がしますね。

2022-12-17 07:47 UTC, bdunderscore commented
色々とコードを書いてるところ申し訳ないですが、サブメニュー制作に関しては長期的なメニュー制作デザインを練りたいので、おそらく今の仕様ではマージできないと思います。新規コンポーネントの場合は将来的な開発予定に合うように慎重にデザインを考えてから導入したい、ということです。

将来的には https://github.com/hai-vr/av3-expressions-menu-hierarchy-editor のような仕様にしようかと思っていますので、その辺の仕様を確定するまではサブメニューを作るだけのコンポーネントを導入できないです（将来的に用途が被るコンポーネントができてしまいそうなので）

また、「別のアセットが追加するメニューに入る」仕様でも、そのアセット引用をどうやってプレハブ化して維持するか、という問題もありまして、他のコンポーネントでも必要になる仕様なので共通規格で解決したいと考えています。

というわけで、現時点で受け入れられるのは、「他のMenu Installerでインストールされるメニューを、Menu Installerの導入先に指定する」の仕様変更や、「同じメニューを複数回導入しない」設定の追加のような、規模の小さい変更ぐらいだと思います。

2022-12-17 12:36 UTC, raiti-chan commented
モジュールを追加しないで、
インストーラーに指定されているメニューのサブメニューをインストール先として指定できるように変更しました。

`AvMenuTreeView` `MenuInstallerEditor` `MenuInstallHook`
に大幅な変更を加えているため、方針にそぐわない可能性がありますので、その場合クローズいたします。

2022-12-18 06:39 UTC, bdunderscore requested changes

2022-12-18 06:39 UTC, bdunderscore commented on Packages/nadena.dev.modular-avatar/Editor/ClonedMenuMappings.cs
> +			// Usually, one menu is rarely duplicated in multiple menus, so don't bother using a Builder
このコメントの意図がよくわかりません。Builderの場合はどういう風になると想定していますか？

2022-12-18 06:39 UTC, bdunderscore commented on Packages/nadena.dev.modular-avatar/Editor/Inspector/AvMenuTreeView.cs
>              }
`installer`と`Installer`は誤解しやすそうなので変数の名前を変更しましょう

2022-12-18 06:39 UTC, bdunderscore commented on Packages/nadena.dev.modular-avatar/Editor/MenuTree.cs
> +		public void AvatarsMenuMapping()
この関数名がなんかクラス名っぽいのでTraverseAvatarMenuとかにしましょう（他のMapping系も同様）

2022-12-18 06:39 UTC, bdunderscore commented on Packages/nadena.dev.modular-avatar/Editor/MenuTree.cs
> +	public class MenuTree
ひとまずinternalにしましょう

また、Installerが単一submenuを追加するのではなく、コントロールを複数追加しうることから結構複雑な実装になっているので、もう少しコメントによる解説をお願いします（理解するのに結構時間がかかった）

2022-12-18 06:39 UTC, bdunderscore commented on Packages/nadena.dev.modular-avatar/Editor/MenuTree.cs
> +					});
138-148ですでにサブメニューを登録しているのに、installerの情報のみが入っている項目を登録する意味がぱっと見分かりませんので、コメントなどで解説お願いします

2022-12-18 06:39 UTC, bdunderscore commented on Packages/nadena.dev.modular-avatar/Editor/ClonedMenuMappings.cs
> +		private static readonly Dictionary<VRCExpressionsMenu, ImmutableArray<VRCExpressionsMenu>> ClonedMappings =
これがArrayになる理由は？（コメントをつけましょう）

2022-12-18 06:39 UTC, bdunderscore commented on Packages/nadena.dev.modular-avatar/Editor/ClonedMenuMappings.cs
> +		private static readonly Dictionary<VRCExpressionsMenu, VRCExpressionsMenu> OriginalMapping =
このマッピングと上のClonedMappingsの違いもドキュメントしましょう

2022-12-18 06:39 UTC, bdunderscore commented on Packages/nadena.dev.modular-avatar/Editor/ClonedMenuMappings.cs
> +	public static class ClonedMenuMappings
ひとまずinternalで

2022-12-18 06:39 UTC, bdunderscore commented on Packages/nadena.dev.modular-avatar/Editor/MenuTree.cs
> +			return immutableBuilder.immutableArray;
ここのキャッシュはそのあとにアイテムが追加した場合ずれます。
Builderとキャッシュを分けるのではなく、普通にImmutableList.Addで追加する方針のほうがおすすめです（内部実装では `O(lg n)` なのでそこまで重くないはず）

2022-12-18 10:12 UTC, raiti-chan commented on Packages/nadena.dev.modular-avatar/Editor/ClonedMenuMappings.cs
> +			// Usually, one menu is rarely duplicated in multiple menus, so don't bother using a Builder
基本的に`ImmutableArray`に`add`されるケースが稀なため(※1)`MenuTree`のようにbuilderを使用せず`ImmutableArray`に直接`add`することを書いたつもりでしたが、
`MenuTree`側をBuilderを使用しないように変えたため、こちらも`ImmutableList`に変更し、コメントを削除しました。

※1 : 同じメニューを複数のインストーラに指定する場合のみ

2022-12-18 10:12 UTC, raiti-chan commented on Packages/nadena.dev.modular-avatar/Editor/Inspector/AvMenuTreeView.cs
>              }
`Installer`を`TargetInstaller`へ変更しました。

2022-12-18 10:13 UTC, raiti-chan commented on Packages/nadena.dev.modular-avatar/Editor/MenuTree.cs
> +		public void AvatarsMenuMapping()
該当する関数の名前を変更しました。

2022-12-18 10:14 UTC, raiti-chan commented on Packages/nadena.dev.modular-avatar/Editor/MenuTree.cs
> +	public class MenuTree
internalへ変更し、コメントを追加しました。

2022-12-18 10:18 UTC, raiti-chan commented on Packages/nadena.dev.modular-avatar/Editor/MenuTree.cs
> +					});
`MenuTree`はコントロール単位ではなくメニュー単位のツリー構造を持ちます。
そのため、子メニューを持たないメニューが指定されてるインストーラの情報が失われてしまうため、インストーラの情報だけ登録する趣旨をコメントに記載しました。

2022-12-18 10:21 UTC, raiti-chan commented on Packages/nadena.dev.modular-avatar/Editor/ClonedMenuMappings.cs
> +		private static readonly Dictionary<VRCExpressionsMenu, ImmutableArray<VRCExpressionsMenu>> ClonedMappings =
複数のインストーラに対して、同じメニューを設定した場合、`RenameParametersHook`内で、それぞれ別のメニューとして複製されます。
そのため、1対多の関係になるので、Array(変更後はList)になります。
その趣旨をコメントとして記載しました。

2022-12-18 10:23 UTC, raiti-chan commented on Packages/nadena.dev.modular-avatar/Editor/ClonedMenuMappings.cs
> +		private static readonly Dictionary<VRCExpressionsMenu, VRCExpressionsMenu> OriginalMapping =
こちらも記載しましたが、現状使われることが無かったので、削除した方がよろしいでしょうか?

2022-12-18 10:23 UTC, raiti-chan commented on Packages/nadena.dev.modular-avatar/Editor/ClonedMenuMappings.cs
> +	public static class ClonedMenuMappings
internalにしました。

2022-12-18 10:35 UTC, raiti-chan commented on Packages/nadena.dev.modular-avatar/Editor/MenuTree.cs
> +			return immutableBuilder.immutableArray;
アイテムを追加した際、キャッシュに再度`ImmutableArray<ChildElement>.Empty`を代入させることでズレることはおそらくないはずですが、
ほかの場所でもAddで追加しているので、そちらの方針に統一しました。

2022-12-20 12:20 UTC, bdunderscore requested changes
おおむね大丈夫そうですね。一個マージミスがありますので、修正していただいて、こちらで少し軽くテストすれば次のバージョンにマージします。PRありがとうございます！

2022-12-20 12:21 UTC, bdunderscore commented on Packages/nadena.dev.modular-avatar/Editor/ClonedMenuMappings.cs
> +		private static readonly Dictionary<VRCExpressionsMenu, VRCExpressionsMenu> OriginalMapping =
ドキュメントされているのでOK

2023-01-02 07:42 UTC, merged