MAProbeAnchorの追加（ModularAvatarでLightProbeを設定できるように）
bdunderscore/modular-avatar pull request #304
Opened 2023-05-17 05:46 UTC by AoiKamishiro

MAProbeAnchorコンポーネントを追加しました。
UIはBoneProxyと似たデザインで、このコンポーネントを付けたオブジェクトの子に含まれる各種RendererコンポーネントのProbeAnchor (LightProbe) を、ターゲットで指定したオブジェクトに変更する機能を持ちます。
ManualBakeとPlayModeで動作を確認しました。
![image](https://github.com/bdunderscore/modular-avatar/assets/40717483/25f58532-8e04-4c0a-af38-a25afa4594bf)

2023-05-21 07:53 UTC, bdunderscore requested changes
提案ありがとうございます！アイデアとしてはよさそうなので、実装のほうはレビューコメントを適用していただけたら採用したいと思います。

また、できればユニットテストを追加していただけると助かります。

2023-05-21 07:53 UTC, bdunderscore commented on Packages/nadena.dev.modular-avatar/Runtime/ModularAvatarProbeAnchor.cs
> +        }
HumanBodyBoneを起点にする必要がないので、`AvatarObjectReference` をご利用ください（CustomPropertyDrawerで表示処理などを自動的にやってくれます）

2023-05-21 07:53 UTC, bdunderscore commented on Packages/nadena.dev.modular-avatar/Editor/Localization/en.json
> +  "probeanchor.err.MovingTarget": "You cannot specify a target object that will be moved by other Modular Avatar components",
この制限は必要ですか？

2023-05-21 07:53 UTC, bdunderscore commented on Packages/nadena.dev.modular-avatar/Editor/ProbeAnchorProcessor.cs
> +                }
エラーメッセージ内容と実際の制限が異なっている模様です。

2023-05-21 11:03 UTC, AoiKamishiro commented
ありがとうございます。
Humanoidボーンに依存しない形への修正、不必要な制約の排除、不要な翻訳の削除、中国語の翻訳の追加、単体テストの追加を行いました。確認をお願いいたします！

2023-06-05 09:53 UTC, bdunderscore approved these changes

2023-06-05 09:53 UTC, merged