feat: MA World Fixed Object
bdunderscore/modular-avatar pull request #385
Opened 2023-08-13 06:31 UTC by anatawa12

Closes #299

2023-08-13 07:20 UTC, bdunderscore requested changes
ユニットテストも追加するようお願いします 🙏

2023-08-13 07:20 UTC, bdunderscore commented on Packages/nadena.dev.modular-avatar/Editor/Localization/en.json
> +  "worldfixed.quest": "This component has no effect when not placed under the head bone.",
コピペミス？

2023-08-13 07:20 UTC, bdunderscore commented on docs/docs/reference/world-fixed-object.md
> +
この下りが空欄になっているので削除しましょう

2023-08-13 07:26 UTC, bdunderscore commented
Merge Armatureと同様、親からのActive状態を継承する処理を入れたほうがよさそうな気もする…？

2023-08-13 07:27 UTC, anatawa12 commented on Packages/nadena.dev.modular-avatar/Editor/Localization/en.json
> +  "worldfixed.quest": "This component has no effect when not placed under the head bone.",
ですね。
```suggestion
  "worldfixed.quest": "This component is not compatible with the standalone Oculus Quest and will have no effect.",
```

2023-08-13 07:28 UTC, anatawa12 commented
> Merge Armatureと同様、親からのActive状態を継承する処理を入れたほうがよさそうな気もする…？

あったほうが良さそうですね。

2023-08-14 00:01 UTC, bdunderscore commented
旅行に出るため、レビューは少々遅れます。ご了承ください 🙏

2023-08-22 09:56 UTC, bdunderscore reviewed
確認しました。概ねよさそうですが、現在進行中のプラグインリファクターと干渉しそうなのでマージはもう少し先になりそうです（干渉自体はこちらで解消します）

2023-09-24 07:58 UTC, bdunderscore approved these changes

2023-09-24 07:59 UTC, merged