feat: SetOrInherit mode in MA Mesh Settings for EasySetupOutfit
bdunderscore/modular-avatar pull request #981
Opened 2024-08-11 06:28 UTC by anatawa12

今までのEasySetupOutfitではMA Mesh Settingsを作成する際にSetモードを使用していました。

しかし、これによって意図せず生成された MA Mesh Settings が後に MA Mesh Settings機能を知ったユーザがアバタールートにつけた MA Mesh Settings の動作を上書きしてしまう問題があります。

これの対策として親に Set モードの MA Mesh Settings がない場合にはSetとして、ある場合にはInheritとして動作するモードを追加します。

参考: https://discord.com/channels/1157554007095652392/1165677124993155102/1196048760954966087

2024-08-11 21:11 UTC, bdunderscore requested changes
あとで実装予定だった機能なので助かります 🙏 

間違えてチェックインしたファイルもあるみたいなので確認お願いします

2024-08-11 21:11 UTC, bdunderscore commented on Editor/CheckBoneMapping.cs
> +        public static void Open() => GetWindow<CheckBoneMappingWindow>();
間違えて追加した？

2024-08-11 21:11 UTC, bdunderscore commented on Editor/Inspector/MeshSettingsEditor.cs
> +            if (_prop_inherit_probe_anchor.enumValueIndex is (int) ModularAvatarMeshSettings.InheritMode.Set or (int) ModularAvatarMeshSettings.InheritMode.SetOrInherit)
初めてこの` or `シンタックスを見た・・・（便利そう）

2024-08-11 21:11 UTC, bdunderscore commented on Editor/MeshSettingsPass.cs
> +                    throw new System.InvalidOperationException($"Logic failure: invalid InheritMode: {currentMode}");
例外が違うのは何か理由ありますか？

2024-08-12 05:22 UTC, bdunderscore commented
メモ　要ドキュメンテーション更新（リファレンス、衣装作者向けページ）

2024-08-12 06:03 UTC, anatawa12 commented on Editor/CheckBoneMapping.cs
> +        public static void Open() => GetWindow<CheckBoneMappingWindow>();
あー誤追加です。すみません

2024-08-12 06:05 UTC, anatawa12 commented on Editor/Inspector/MeshSettingsEditor.cs
> +            if (_prop_inherit_probe_anchor.enumValueIndex is (int) ModularAvatarMeshSettings.InheritMode.Set or (int) ModularAvatarMeshSettings.InheritMode.SetOrInherit)
C# 9で追加された or patternですね。switchで使ったnotや今回は使ってませんがandも追加されました。

参考 https://ufcpp.net/study/csharp/cheatsheet/ap_ver9/#pattern-v3

2024-08-12 06:09 UTC, anatawa12 commented on Editor/MeshSettingsPass.cs
> +                    throw new System.InvalidOperationException($"Logic failure: invalid InheritMode: {currentMode}");
`currentMode`はすでにチェックされてて例外が発生する == 常にバグなので`InvalidOperationException`に、`srcMode`はバージョン不整合等でバグではなく発生する可能性があるので別の例外にしました。

2024-08-13 01:45 UTC, bdunderscore approved these changes

2024-08-13 01:45 UTC, bdunderscore commented
ありがとうございます！

2024-08-13 01:45 UTC, merged

2024-09-25 01:48 UTC, Sayamame-beans commented
> メモ　要ドキュメンテーション更新（リファレンス、衣装作者向けページ）

忘れてしまっていそうな予感(MA Mesh Settingsのdocsを参照)